#pragma once 

#define BLUESTREET_DEVICE 0x8000
#define IOCTL_BLUESTREET_SEND_DATA CTL_CODE(BLUESTREET_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_BLUESTREET_RECEIVE_DATA CTL_CODE(BLUESTREET_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_BLUESTREET_DEBUG_PRINT CTL_CODE(BLUESTREET_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _sMSG {
	WCHAR Path[256];
	WCHAR Dlls[256];
} sMSG;
typedef struct _sMSG* PsMSG;


